server:
  port: 8080
spring :
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: mongodb://user:user1234@3.37.127.25:27017/user
  kafka:
    bootstrap-servers: 3.37.127.25:9092
    consumer:
      group-id: user-manager-group
    topic:
      sign-out-topic: "userManager.signOut"

logging:
  file:
    name: "/log/user-manager.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB
  pattern:
    console: