server:
  port: 8001
spring :
  jackson:
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: mongodb://localhost:27017/UserManager
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-manager-group
    topic:
      sign-out-topic: "userManager.signOut"
